version: '3.8'
services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8721:8721"
    networks:
      - microservices-net
    environment:
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
      
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true
