name: Build Microservices

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper (Linux/macOS)
        if: runner.os != 'Windows'
        run: chmod +x user-service/gradlew

      - name: Build and test user-service with Gradle
        working-directory: user-service
        run: |
          ./gradlew clean build
        shell: bash

      - name: Build and test on Windows
        if: runner.os == 'Windows'
        working-directory: user-service
        run: gradlew.bat clean build
